### ISSUE TITLE
How to remove footer/navigation bar in android/ios?

### ISSUE THREAD

**Issue by knnthcrtl1** [proyecto26/react-native-inappbrowser#235] opened 2021-02-11 00:51 UTC
![navbar](https://user-images.githubusercontent.com/38338549/107591798-5a188900-6c46-11eb-8715-6c549179f774.png)

**Comment by jdnichollsc** [comment] 2021-02-11 04:44
Duplicate of #229

**Closed** 2021-02-11 04:44 UTC
