### ISSUE TITLE
Android.permission.QUERY_ALL_PACKAGES was automatically added to Manifest

### ISSUE THREAD

**Issue by sharmal33** [proyecto26/react-native-inappbrowser#363] opened 2022-06-21 04:44 UTC
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-inappbrowser-reborn@3.6.3` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-inappbrowser-reborn/android/src/main/AndroidManifest.xml b/node_modules/react-native-inappbrowser-reborn/android/src/main/AndroidManifest.xml
index 6aaceca..602e13e 100644
--- a/node_modules/react-native-inappbrowser-reborn/android/src/main/AndroidManifest.xml
+++ b/node_modules/react-native-inappbrowser-reborn/android/src/main/AndroidManifest.xml
@@ -3,7 +3,6 @@
           package="com.proyecto26.inappbrowser">
 
     <uses-permission android:name="android.permission.INTERNET" />
-    <uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" />
 
     <application>
         <activity
@@ -16,4 +15,3 @@
         </intent>
     </queries>
 </manifest>
-  
\ No newline at end of file
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by ploveland** [comment] 2022-06-27 15:59
We have the same issue - we are getting warnings from Google requiring the removal of `QUERY_ALL_PACKAGES` from our app, but it's only in this package. Will this be removed or is it necessary?

**Comment by mark-quinn** [comment] 2022-06-28 09:36
Same issue we are seeing too. Is this permission required for this package? Would be good to get this resolved soon as there's a deadline of the 12th of July set by Google.

**Comment by edgaraskazlauskas** [comment] 2022-07-01 05:10
Same, I haven't noticed any issues testing without the permission locally, but don't have the courage to release the app with this permission removed to prod.

**Comment by jetako** [comment] 2022-07-13 20:41
I believe the permission allows for this `queries` tag in `AndroidManifest.xml`:
```
    <queries>
        <intent>
            <action android:name="android.support.customtabs.action.CustomTabsService" />
        </intent>
    </queries>
```
Looks like the query is used to figure out the default Android browser. I tested without the permission on a release build and it still works on my device, but I don't know what happens if Chrome isn't installed.

@zeritte your solution works great! I confirmed that `QUERY_ALL_PACKAGES` is no longer in the merged manifest. However, I also needed to add `xmlns:tools="http://schemas.android.com/tools"` to the `manifest` tag.

I think most users of this library would prefer that sensitive permissions aren't required by default, unless there is a critical need for it.

**Comment by rugiaDev** [comment] 2022-07-21 05:45
@jetako @zeritte 
I removed the `QUERY_ALL_PACKAGES` permission and stopped using chrome.
Then it opened with samsung browser.
I'm worried because I don't know when that permission will be used...

**Comment by deepfinessed** [comment] 2022-07-22 01:02
Commenting here in case it helps others experiencing this issue:

My app was rejected because it included the offending permission, and I had offending releases on multiple tracks, Internal and Closed Beta. Unfortunately, as this issue blocks updates, I could not release an app removing the permission on the internal track because there was an offending release on the Closed Track, and I could not release on the Closed Track because there was an offending release on the Internal Track.

The solution in this case according to Google Play Support is to fill out the form justifying your use of the permission with dummy information - while this will result in a rejection of the release, it does clear the offending bundle from the release track. Subsequent releases without the permission can then go forward.

**Comment by RayHughes** [comment] 2022-07-22 20:53
> The solution in this case according to Google Play Support is to fill out the form justifying your use of the permission with dummy information - while this will result in a rejection of the release, it does clear the offending bundle from the release track. Subsequent releases without the permission can then go forward.

Seriously thank you for this. I have spent the better part of 2hrs trying to figure out why the new build was being rejected despite it not being in the manifest.

**Comment by ChristieRobson** [comment] 2022-07-26 07:21
> > The solution in this case according to Google Play Support is to fill out the form justifying your use of the permission with dummy information - while this will result in a rejection of the release, it does clear the offending bundle from the release track. Subsequent releases without the permission can then go forward.
> 
> Seriously thank you for this. I have spent the better part of 2hrs trying to figure out why the new build was being rejected despite it not being in the manifest.

Has anyone been able to get their app through review since patching?

**Comment by codal-mpawar** [comment] 2022-07-26 16:26
@ChristieRobson @RayHughes can you please guys share what you added in the description. Can you please help me on this. I blocked with this issue
And video is required ?

**Comment by RayHughes** [comment] 2022-07-26 16:29
I have not released a new version yet. However in the form I did link to the issue and stated that the next build does not have the permission in place and I simply filled out the form because it was blocking upload.

You might be getting rejected because you have tracks with an active build that uses the permission. Try checking them.

**Comment by Herael** [comment] 2022-07-27 12:49
Hello, 

I added in my AndroidManifest.xml the remove of the `QUERY_ALL_PACKAGES` permission: 

```<!-- Removing the access InAppBrowser package adds -->
<uses-permission tools:node="remove" android:name="android.permission.QUERY_ALL_PACKAGES" />
```

and I also added a patch like yours but I still get the following error: 

`Google Api Error: Invalid request - This release includes the QUERY_ALL_PACKAGES permission, which hasn't been declared in Play Console.`

Did you also face this error despite the patch and the removal of the condition in the AndroidManifest? 

I need to deploy my application but apparently, the library will not be patched soon ... :/

Thanks and have a nice day ! ☀️

**Comment by jdnichollsc** [comment] 2022-07-29 17:11
Sorry for the delay folks, My Mac stopped working :/ 
BTW, let me publish a new version in a few hours! <3

**Comment by jdnichollsc** [comment] 2022-07-29 17:20
Duplicates of #355

**Closed by jdnichollsc** 2022-07-29 17:20 UTC
