### ISSUE TITLE
Getting warning as "Another InAppBrowser is already being presented" 

### ISSUE THREAD

**Issue by nihp** [proyecto26/react-native-inappbrowser#131] opened 2019-12-26 05:13 UTC
I am getting warning as "**Another InAppBrowser is already being presented**"  after the click on the link second time without closing the previously opened window and failed to open the link.

Steps to reproduce:

1. Clock on the link which needs to be open
2. It will open the url
3. Then I swipe from left to right
4. It goes to the previous screen
5. Then I tried to open another link 
6. It failed to open and shows the above warning in my simulator

Note: If I click done in 3rd step means it works well. But here I need will swipe to go back. In this cases how can I make it to work.

I am using **react-native version ==> 0.61.5**

**Comment by jdnichollsc** [comment] 2020-01-03 18:38
Can you share your code please?

**Comment by frankyjuang** [comment] 2020-01-04 10:34
I think I have it fixed. Please check the pr

**Comment by jdnichollsc** [comment] 2020-01-04 15:22
Ohh thanks, let me check and publish a new version this weekend 👍

**Comment by jdnichollsc** [comment] 2020-01-07 19:44
Done! thanks for your help! ❤️

**Comment by klaaz0r** [comment] 2020-02-03 21:33
I am getting this on the latest version with just using the example code.

**Comment by mstfymrtc** [comment] 2020-02-12 02:32
Also I'm getting same error on iPhone 11. But works on iPhone 8. Both are iOS 13.1.

**Comment by joshbuchea** [comment] 2020-03-03 22:20
I was also getting the **Another InAppBrowser is already being presented** error message with the latest version (downloaded `3.3.4` today) when using the example code in an app with React Native `0.60.5`. Tested on the iOS Simulator with iPhone X on iOS `13.3`.

Was able to resolve by:

- Call `InAppBrowser.open(url)` without options (omit the 2nd param)
- Close bundler
- Re-build app for iOS

💥hopefully that helps a few folks, as I wasted ~45 minutes on this issue

**Comment by jdnichollsc** [comment] 2020-03-04 02:13
mmm very odd, reopening to have this issue in mind, any pull request is welcome! 👍

**Comment by prayuditb** [comment] 2020-03-16 09:33
I also facing this issue. but unfortunately, the solution from  @joshbuchea didn't work for me.
I'm using version `v3.3.4`

**Comment by claudiozam** [comment] 2020-04-05 01:47
The solution from @joshbuchea didn't work for me :(
I'm using version v3.3.4

**Comment by jdnichollsc** [comment] 2020-04-08 03:55
@prayuditb @claudiozam in what platform? In Android, check if this configuration works for you https://github.com/proyecto26/react-native-inappbrowser/blob/master/example/android/app/src/main/AndroidManifest.xml#L13

**Comment by jdnichollsc** [comment] 2020-04-08 06:33
One little question, are you using `closeAuth` before?

**Comment by claudiozam** [comment] 2020-04-08 16:03
@jdnichollsc in IOS.  We are not using closeAuth.

**Comment by jdnichollsc** [comment] 2020-04-08 16:16
Check the last version 3.4.0 and let me know, or if you can check the follow validation and send a pull request, always is welcome! https://github.com/proyecto26/react-native-inappbrowser/blob/master/index.js#L161

**Comment by jdnichollsc** [comment] 2020-04-08 22:06
I think we can remove that validation and clear any listener is the `openAuth` function is called again, what do you think guys?

**Comment by jdnichollsc** [comment] 2020-04-22 16:54
After checking in a personal app, this error is happening here https://github.com/proyecto26/react-native-inappbrowser/blob/master/ios/RNInAppBrowser.m#L274
So it looks like `safariViewControllerDidFinish` is not working as expected, and I don't understand why

**Comment by jdnichollsc** [comment] 2020-04-22 22:32
Hello folks! @nihp @frankyjuang @klaaz0r @mstfymrtc @joshbuchea @prayuditb @claudiozam can you help me debugging `InAppBrowser` from your apps and let me know if this method is not being called (it's used to clear the promises when the browser is closed)
<img width="966" alt="debug-xcode" src="https://user-images.githubusercontent.com/2154886/80040018-c57a4a00-84be-11ea-985c-fde1e5ef4721.png">

I can't reproduce this issue from demo project
Thanks in advance! 👍

**Comment by sadikyalcin** [comment] 2020-04-28 15:55
I am also facing this issue. I simply close the browser and open it again. This solution seems to work.

```
  async openInAppBrowser(_entity) {
    try {
      await InAppBrowser.isAvailable();
      InAppBrowser.open(_entity.url, {
        // iOS Properties
        dismissButtonStyle: 'close',
        preferredBarTintColor: themeVars.primaryColor,
        preferredControlTintColor: 'white',
        animated: true,
        ephemeralWebSession: false,
        // Android Properties
        showTitle: true,
        toolbarColor: themeVars.gradientPurple,
        secondaryToolbarColor: 'black',
        enableUrlBarHiding: false,
        enableDefaultShare: false,
        forceCloseOnRedirection: true,
      })
        .then(result => {
          realm.write(() => {
            realm.create(
              'CourseEntity',
              {
                nid: parseInt(_entity.nid, 10),
                opened: true,
              },
              'modified',
            );
          });
        })
        .catch(_error => {
          InAppBrowser.close();
          this.openInAppBrowser(_entity);
          //Linking.openURL(_entity.url);
        });
    } catch (error) {
      Alert.alert(error.message);
    }
  }
```

**Comment by lucasrodes** [comment] 2020-05-18 22:01
any updates? getting this problem on iOS 13.4, running the emulator.

**Comment by jdnichollsc** [comment] 2020-05-19 05:48
@lucasrodes in your case it's ok because you don't need **partialCurl** transition :)

**Comment by claudiozam** [comment] 2020-06-22 23:22
@jdnichollsc We were able to reproduce the error (Tested on a real device - IPhone X and IPhone 8: IOS 13.5.1)

1- Launch the InAppBrowser by clicking a button. 
2- The InAppBrowser pops up. 
3- Close the InAppBrowser (by pressing the "Close" button in the top left corner) right after (before the website is rendered).
4- Try to open the InAppBrowser again using the button from step 1. 
5- The InAppBrowser pops up for a "milisecond"  and gets closed right after automatically without human intervention.

**Comment by jdnichollsc** [comment] 2020-06-22 23:30
@claudiozam Can you provide a sample app that exhibits this issue? It would be a lot simpler to debug if we had a sample, thanks!

**Comment by claudiozam** [comment] 2020-06-23 13:41
@jdnichollsc the method **(void) flowDidFinish** is not being called. Saludos y gracias!!!

**Comment by jdnichollsc** [comment] 2020-06-23 15:45
Do you know if **safariViewControllerDidFinish** is not been called too?

**Comment by claudiozam** [comment] 2020-06-23 16:02
@jdnichollsc the method **safariViewControllerDidFinish** is not being called too

**Comment by claudiozam** [comment] 2020-06-23 16:13
Also i was able to reproduce the issue in the example app. But it was difficult to test it (No warning all the time...).

I used different URLs.
https://bit.ly/2AS3txf
https://httpstat.us/301?sleep=1000
https://httpstat.us/302?sleep=1000
https://httpstat.us/301?sleep=5000

**Comment by jdnichollsc** [comment] 2020-06-23 18:28
Thanks, let me check! 👍

**Comment by claudiozam** [comment] 2020-06-24 11:55
The methods flowDidFinish and safariViewControllerDidFinish are not being called if you are using a modal + InAppBrowser in IOS. You must close the modal and wait a couple of seconds.  But I don't know why i was hable to reproduce the message "Another InAppBrowser is already being presented" in the example App. RN Fast Refresh issue?

**Comment by jdnichollsc** [comment] 2020-06-24 16:03
Are you updating the code while the browser is opened?

**Comment by claudiozam** [comment] 2020-06-24 17:51
No, only before the browser is open and after the user close it

**Comment by jacquesdev** [comment] 2020-07-24 11:21
My temporary fix for this issue, is do a try/catch, and then in the catch manually close the browser instance and then re-open it.

```
await InAppBrowser.close()
InAppBrowser.open(url, config)
```

A bit of a hack, but the users get a good experience

**Comment by nhanha** [comment] 2020-08-25 09:36
@jacquesdev 👍 Your are number 1.

**Comment by jasperkuperus** [comment] 2020-08-27 06:18
> Are you updating the code while the browser is opened?

This was indeed my issue: Open the `InAppBrowser`, then modify your code, resulting in a refresh. Close the `InAppBrowser`, reopen and you get this error. So that's related to reloading the app while the `InAppBrowser` is open.

My solution to this is try to not refresh your app while having the `InAppBrowser` opened. Once this did happen and you get this error: Kill the app and re-open it. It's not pretty, but it works for me.

**Comment by jasperkuperus** [comment] 2020-09-15 15:06
I ran into a new scenario, where opening an in app browser twice, the second time it crashes. Nothing really helped me. The `await InAppBrowser.close()` didn't help, and also the `await InAppBrowser.isAvailable()` didn't help me (always results in true, even when it crashes). The first in app browser is certainly closed before opening the second.

I ended up doing a very ugly hack, something along these lines:

```
async function open() {
  try {
    await InAppBrowser.open('...', {});
  } catch (error) {
    await new Promise((resolve) => setTimeout(resolve, 500));
    await InAppBrowser.open('...', {});
  }
}
```

@jdnichollsc @frankyjuang Can we have another look at this issue? These hacks really shouldn't be necessary...

**Comment by frankyjuang** [comment] 2020-09-16 05:55
> @jdnichollsc @frankyjuang Can we have another look at this issue? These hacks really shouldn't be necessary...

I'm not using this anymore. Sorry cant help

**Comment by jdnichollsc** [comment] 2020-09-16 07:31
Let me check if I can deploy a new version this weekend, sorry for the delay

**Comment by janpe** [comment] 2020-09-17 10:36
I seem to be getting this error when in a case like this: I have a modal (`react-native-modal`) where I have a button. When I press the button I close the modal and open the browser, but the closing animation of the modal seems to break the browser. The browser slides up to open but when the modal close animation happens the browser closes too. If I wait for the modal to close before opening the browser everything seems to work all normal.

**Comment by indapublic** [comment] 2020-10-13 01:53
Works for me after removing `modalTransitionStyle: 'partialCurl',`

**Comment by jdnichollsc** [comment] 2020-10-15 07:35
Please debug the last changes from `develop` branch, there's a pending PR of the new version 3.5.0 https://github.com/proyecto26/react-native-inappbrowser/pull/195

**Comment by Sunakujira1** [comment] 2020-10-20 18:09
I am experiencing the exact same issue as @janpe reported above with the latest version, 3.5.1.

**Comment by jdnichollsc** [comment] 2020-10-21 00:35
Feel free to attach a repository in order to reproduce this issue and I'll be happy to re-open this issue and take a look 👍

**Closed by jdnichollsc** 2020-10-21 00:35 UTC
Labels: help wanted

**Comment by omer-to** [comment] 2021-07-24 13:45
Hello,

I'm facing the same issue using with aws-amplify.

I'm using the following versions:
`"react-native": "0.64.1"`
`"react-native-inappbrowser-reborn": "^3.6.3"`

```ts
import Amplify from 'aws-amplify'
import { Linking } from 'react-native';
import InAppBrowser from 'react-native-inappbrowser-reborn';

Amplify.configure({
      Auth: {
            userPoolId: 'COGNITO_USER_POOL_ID',
            userPoolWebClientId: 'COGNITO_USER_POOL_WEBCLIENT_ID',
            region: 'eu-central-1',
            oauth: {
                  domain: 'auth.myApp',
                  scope: ['email', 'profile', 'openid',],
                  redirectSignIn: 'myApp://',
                  redirectSignOut: 'myApp://',
                  responseType: 'code',
                  async urlOpener(url: string, redirectUrl: string) {
                              const response = await InAppBrowser.openAuth(url, redirectUrl, {
                                    showTitle: false,
                                    enableUrlBarHiding: true,
                                    enableDefaultShare: false,
                                    ephemeralWebSession: false,
                              });
                              if (response.type === 'success') await Linking.openURL(response.url);
                  }
            }
      },
})
```

**Comment by nathanwkwong** [comment] 2022-09-27 03:17
My case trigger the warning: 
1. open in app browser with `InAppBrowser.open(url)`
2. minimise the app, and open a deep link than will trigger another call of InAppBrowser.open(url)

My workaround so far:
1. try to close and open the browser with `InAppBrowser.close()` and `InAppBrowser.open(promotionUrl)` 
2. and a retry callback on the `.catch()` of `InAppBrowser.open(promotionUrl)` 

`   
     let retryCounter = 0;
   const openBrowser = () => {
              InAppBrowser.close();
              InAppBrowser.open(promotionUrl)
                  .then(() => {
                     // success handling
                  })
                  .catch(() => {
                      if (retryCounter < 2) {
                          setTimeout(() => {
                              retryCounter++;
                              openBrowser();
                          }, 1000);
                    } else {
                        // failed handling
                    }
                  });
          };

        openBrowser();`

**Comment by abdalla-finder** [comment] 2024-09-26 03:34
any update?
