### ISSUE TITLE
Crash ChromeTabsManagerActivity.java line 52

### ISSUE THREAD

**Issue by wilau2** [proyecto26/react-native-inappbrowser#150] opened 2020-04-06 13:39 UTC
10 crashes affecting 6 users in the last 30 days
Android 9 and 10 
HUAWEI
Google
LGE
motorola

```
ChromeTabsManagerActivity.java line 52
com.proyecto26.inappbrowser.ChromeTabsManagerActivity.onCreate
```

### Which platform(s) does your issue occur on?
- Android 

### Please, provide the following version numbers that your issue occurs with:

- react-native: 61.5
- react-native-app-auth: 5.1.1
- react-native-inappbrowser-reborn: 3.3.4

![ChromeTabsBug](https://user-images.githubusercontent.com/5473183/78564428-693ed700-77ea-11ea-822e-dcdb7088534d.png)

**Comment by jdnichollsc** [comment] 2020-04-08 03:47
Please attach any reproducible demo 👍

**Comment by qwertypomy** [comment] 2020-05-26 11:25
Same crashes happens with my app.

```
"react-native": "0.62.2"
"react-native-inappbrowser-reborn": "3.3.4"
```
## Details from crashlytics: 

### Platform: 
Android 8, Android 9, Android 10

### Devices:
Galaxy A20e
Galaxy A80
Galaxy S8
Galaxy S10+
Galaxy S10
Galaxy S9
Galaxy A71
Galaxy A50
Galaxy A10
Motorola one
Pixel 4 XL
LG G7 ThinQ


### ChromeTabsManagerActivity.java line 52
#### com.proyecto26.inappbrowser.ChromeTabsManagerActivity.onCreate 

```
Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{com.myapppp.client/com.proyecto26.inappbrowser.ChromeTabsManagerActivity}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://www.myapppp.com/... flg=0x4000000 (has extras) }
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3488)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3635)
android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:83)
android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2175)
android.os.Handler.dispatchMessage (Handler.java:107)
android.os.Looper.loop (Looper.java:237)
android.app.ActivityThread.main (ActivityThread.java:7860)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1075)
```

```
Caused by android.content.ActivityNotFoundException
No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://www.myapppp.com/... flg=0x4000000 (has extras) }
android.app.Instrumentation.checkStartActivityResult (Instrumentation.java:2071)
android.app.Instrumentation.execStartActivity (Instrumentation.java:1717)
android.app.Activity.startActivityForResult (Activity.java:5250)
android.app.Activity.startActivityForResult (Activity.java:5208)
android.app.Activity.startActivity (Activity.java:5579)
android.app.Activity.startActivity (Activity.java:5547)
com.proyecto26.inappbrowser.ChromeTabsManagerActivity.onCreate (ChromeTabsManagerActivity.java:52)
android.app.Activity.performCreate (Activity.java:7955)
android.app.Activity.performCreate (Activity.java:7944)
android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1307)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3463)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3635)
android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:83)
android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2175)
android.os.Handler.dispatchMessage (Handler.java:107)
android.os.Looper.loop (Looper.java:237)
android.app.ActivityThread.main (ActivityThread.java:7860)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1075)
```

**Comment by qwertypomy** [comment] 2020-05-26 11:28
@jdnichollsc Can you reopen this issue please?

**Comment by jdnichollsc** [comment] 2020-05-26 15:08
@qwertypomy Please attach a reproducible demo to be able to reopen this issue 👍

**Comment by qwertypomy** [comment] 2020-05-26 15:20
I can't reproduce this, but it happens to some users. Stack trace is quite descriptive, maybe you have some thoughts? @jdnichollsc

**Comment by jdnichollsc** [comment] 2020-05-26 15:43
Nothing, it's very odd, I don't understand what's the problem with NativeScript creating the Android Activity here, maybe you can ask from Slack and StackOverflow to see if exist the same issue with other libraries too

**Comment by GertjanReynaert** [comment] 2020-06-02 12:36
Can you try replicating with google chrome disabled?

The user reporting this crash to me, later sent an email stating that if he installed chrome in his work profile on his phone, the issue disappeared. I tried on my own android phone by disabling google chrome, and I instantly got the same issue.

**Comment by wilau2** [comment] 2020-06-02 17:21
I could reproduce as well by disabling chrome.

**Comment by ssuchanowski** [comment] 2020-06-26 12:39
I think this can be closed as PR went in.

**Comment by wilau2** [comment] 2020-06-29 14:44
Works for me on version `^3.4.0`

**Comment by ssuchanowski** [comment] 2020-06-29 15:45
I don't think there is a new release including fix for this. You reported this on Apr 6th and 3.4.0 went live Apr 8th :P

**Comment by jdnichollsc** [comment] 2020-06-29 20:05
Sorry, the next release is in progress :)

**Comment by ssuchanowski** [comment] 2020-06-29 22:01
Great @jdnichollsc, thanks!

**Comment by jacquesdev** [comment] 2020-07-09 22:32
Hello @jdnichollsc - any idea when the next release will be released.

We have just put this into production, and I noticed the crash from our logs, so the sooner we can get this fixed the better.

Thanks for your hard work on this one!

**Comment by ssuchanowski** [comment] 2020-07-10 08:12
we use `develop` branch for now

**Comment by milesj** [comment] 2020-09-03 16:52
This is blocking our release. Is there an update on when this will be released?

**Comment by jacquesdev** [comment] 2020-09-03 17:40
@milesj use the develop branch

**Comment by isidoro98** [comment] 2020-09-23 09:10
Any updates on when a fix will be released?

**Comment by jdnichollsc** [comment] 2020-10-15 07:37
Please debug the last changes from `develop` branch, there's a pending PR of the new version 3.5.0 https://github.com/proyecto26/react-native-inappbrowser/pull/195

**Closed by jdnichollsc** 2020-10-15 07:37 UTC
Labels: bug

**Comment by Abhishek2250** [comment] 2022-07-04 08:24
I'm still getting this crash from google play.

version:
"react-native-inappbrowser-reborn": "^3.6.3",
"react-native": "^0.68.1",

Log:
FATAL EXCEPTION: Thread-4
Process: com.App_name, PID: 6968
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.App_name/com.proyecto26.inappbrowser.ChromeTabsManagerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.drawable.Drawable.isProjected()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:10)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:7)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:1)
	at androidx.test.espresso.base.UiControllerImpl.loopMainThreadForAtLeast(UiControllerImpl.java:7)
	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:4)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:4)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:21)
	at androidx.test.espresso.ViewInteraction.-$$Nest$mdoPerform(Unknown Source:0)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:6)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.drawable.Drawable.isProjected()' on a null object reference
	at android.graphics.drawable.LayerDrawable.isProjected(LayerDrawable.java:417)
	at android.view.View.invalidateInternal(View.java:16438)
	at android.view.View.invalidate(View.java:16398)
	at android.view.View.setBackgroundDrawable(View.java:21584)
	at com.android.internal.policy.DecorView.setWindowBackground(DecorView.java:939)
	at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2626)
	at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2672)
	at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2071)
	at android.app.ActivityTransitionState.setEnterActivityOptions(ActivityTransitionState.java:160)
	at android.app.Activity.performCreate(Activity.java:7144)
	at android.app.Activity.performCreate(Activity.java:7127)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:2)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
	... 25 more
