### ISSUE TITLE
handling POST 

### ISSUE THREAD

**Issue by FrancisLeigh** [proyecto26/react-native-inappbrowser#230] opened 2021-02-01 10:39 UTC
We are using [react-native-app-auth](https://github.com/FormidableLabs/react-native-app-auth) to authenticate a user with the PKCE auth flow.

`react-native-app-auth` opens a custom-tab to authenticate the user which means when the user chooses to log out and we make the correct calls to our revocation endpoint which clears our session cookies, the session is still valid in the cache of the custom-tab... I have tried clearing all cookies using a library like `react-native-cookies` but to no avail. 

Instead what I am trying now is to use your library to open a custom-tab and make the same POST to our revocation endpoint so that the custom tabs 'cookies are cleared. 

Is making a `POST` supported at all?

### Which platform(s) does your issue occur on?
- Both 
- Both
- Both

### Please, provide the following version numbers that your issue occurs with:
```ruby
react-native-inappbrowser-reborn: ^3.5.1
react-native-cli: 2.0.1
react-native: 0.63.2
```

Thank you

**Comment by jdnichollsc** [comment] 2021-02-01 16:30
Sorry, I don't understand your point about a POST request, why is that related with this library?
Duplicate of #145

**Closed by jdnichollsc** 2021-02-01 16:30 UTC
