### ISSUE TITLE
Android default browser callback not working

### ISSUE THREAD

**Issue by NQuirmbach** [proyecto26/react-native-inappbrowser#171] opened 2020-07-17 07:08 UTC
Hi,

I have an issue on android. If the user has selected any other browser than chrome as defaul the callback won't work. The deep link opens the app, but then does not execute the follow up code after the openAuth call.

Is only chrome as default browser supported or should other browser work as well?

BR Nils

**Comment by jdnichollsc** [comment] 2020-07-19 01:02
A fix for this will be included in the next release, duplicate of https://github.com/proyecto26/react-native-inappbrowser/issues/107

**Closed by jdnichollsc** 2020-07-19 01:02 UTC
