### ISSUE TITLE
InAppBrowser does not close on android 5.1.1

### ISSUE THREAD

**Issue by Daha62** [proyecto26/react-native-inappbrowser#60] opened 2019-04-08 06:50 UTC
Hi there,

I am using your plugin, but suddenly faced with problem on android 5.1.1. InAppBrowser opens link correctly with type - dismiss, but every time u want to close it it opens again. If i want to make a force close - it does nothing.

> React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 39.18 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.7.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.3, 26.0.0, 26.0.2, 26.0.3, 27.0.3, 28.0.3
        System Images: android-19 | ARM EABI v7a, android-19 | Google APIs ARM EABI v7a, android-25 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4670197
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.2 => 0.59.2 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

**Comment by Rizwanilahi** [comment] 2019-04-08 08:12
I am also facing this issue on Android 6.0.1

**Comment by jdnichollsc** [comment] 2019-04-12 16:39
I'm going to check that at weekend, Any pull request is welcome in the meantime! 👍

**Comment by jdnichollsc** [comment] 2019-04-17 04:18
I need a demo to reproduce this issue, please let me know

**Comment by Daha62** [comment] 2019-04-18 05:36
@jdnichollsc, I've just use
`InAppBrowser.open('SOME_LINK')`

And got unclosable browser.
And the BrowserResult type is _dismiss_ instead of _cancel_ (I checked it on other android and ios devices)

**Comment by jdnichollsc** [comment] 2019-04-18 08:27
I can't reproduce this issue from Android 5.1.1 with the example project of this plugin, please attach a reproducible demo
<img width="877" alt="Captura de Pantalla 2019-04-18 a la(s) 3 21 34 a  m" src="https://user-images.githubusercontent.com/2154886/56347047-18714100-6189-11e9-8ab0-7e09124bfac4.png">

**Comment by Daha62** [comment] 2019-04-18 09:37
Of course,
![Снимок экрана 2019-04-18 в 14 32 29](https://user-images.githubusercontent.com/6141193/56351847-6c127780-61e7-11e9-81aa-1390fd287a4e.png)

**Comment by jdnichollsc** [comment] 2019-04-21 09:20
What's that?

**Comment by Daha62** [comment] 2019-04-22 04:56
It's the answer of response as in ur screenshots.

**Comment by jdnichollsc** [comment] 2019-05-05 22:31
@Daha62 try with the last version please and let me know 👍

**Comment by Daha62** [comment] 2019-05-06 05:37
@jdnichollsc thank u for ur updates. But the problem is still is still exist (

![image](https://user-images.githubusercontent.com/6141193/57208037-d189a500-6fea-11e9-8e5b-5af384d0bf26.png)

When I try to close it - browser opens again.

**Comment by jdnichollsc** [comment] 2019-05-06 05:43
Are you using `android:launchMode="singleTask"`?

**Comment by jdnichollsc** [comment] 2019-05-06 05:59
Can you attach a reproducible demo? I can't help you without that, sorry

**Comment by Daha62** [comment] 2019-05-06 07:36
> Are you using android:launchMode="singleTask"?
yep

**Comment by Daha62** [comment] 2019-05-06 07:42
https://drive.google.com/open?id=1SGonNvt0C2TzFw-ngNAA0Nb-7zhjKjgG

**Comment by jdnichollsc** [comment] 2019-05-06 14:28
try without `android:launchMode="singleTask"`, let me check your link at night 👍

**Comment by Daha62** [comment] 2019-05-07 03:42
tried without _singleTask_ mode, but on this device - the same behaviour. 
On others - works as it should.

**Comment by jdnichollsc** [comment] 2019-05-07 04:12
Yeah... and I can't reproduce this issue, so try debugging the plugin and let me know what you find, in the meantime it would be closed 👍

**Comment by ssuchanowski** [comment] 2019-06-23 21:42
Happens to me as well - API 28, Nexus 5X but only on device - emulator seems to be working fine. I will try to investigate more.

**Comment by jdnichollsc** [comment] 2019-06-23 21:54
Thanks @ssuchanowski, because I can't help without a demo or logs of the issue :)

**Comment by WildyDS** [comment] 2019-07-23 07:26
I've also had this issue.
Investigated a lot, found a bug - ChromeTabsManagerActivity activity doesn't restore it's state after onDestroy which may happen even when visually it was not destroyed.

Steps to reproduce (tried on Samsung j320 and Samsung A5 (2016)):
1. Open developer options
2. Turn on "Do not keep activities" in "applications" part
3. Open example app
4. Open browser (here goes our "onDestroy")
5. Try to close browser

The fix is in implementing "onSaveInstanceState" and checking for savedInstanceState in "onCreate" (also some related changes may be needed)

**Comment by jdnichollsc** [comment] 2019-07-23 22:22
@Daha62 @Rizwanilahi @ssuchanowski @WildyDS what happen if you try opening the browser with the `forceCloseOnRedirection` property enabled? Just to know

**Comment by jdnichollsc** [comment] 2019-07-23 22:23
@WildyDS honestly I don't know, but any pull request is welcome mate! 👍

**Comment by Luke-Rogerson** [comment] 2019-07-31 07:34
@WildyDS So you're talking about [the activity lifecycle](https://developer.android.com/guide/components/activities/activity-lifecycle), right? I'd like to help, but don't know enough about native Android code!

**Comment by WildyDS** [comment] 2019-07-31 09:53
> @WildyDS honestly I don't know, but any pull request is welcome mate! 👍

I can actually do it in my spare time but in won't be soon

**Comment by WildyDS** [comment] 2019-07-31 09:54
> @WildyDS So you're talking about [the activity lifecycle](https://developer.android.com/guide/components/activities/activity-lifecycle), right? I'd like to help, but don't know enough about native Android code!

Exactly

**Comment by Luke-Rogerson** [comment] 2019-08-01 08:28
@WildyDS Would you like to pair on it sometime? I'd love to improve my Android dev skillz!

**Comment by marudy** [comment] 2019-11-03 14:44
Hey guys, just run into this as well. Any work around or patch suggested? Thanks

**Comment by jdnichollsc** [comment] 2019-11-12 06:34
@WildyDS thanks for your help, it was fixed in the last version 3.3.0, let me know  👍 https://github.com/proyecto26/react-native-inappbrowser/releases/tag/v3.3.0

**Closed by jdnichollsc** 2019-11-12 06:34 UTC
Labels: bug, help wanted

**Comment by jdnichollsc** [comment] 2019-11-12 21:59
And guys, let me know what you think https://github.com/proyecto26/react-native-inappbrowser/compare/v3.2.0...v3.3.0
