### ISSUE TITLE
Unable to get proper response post authentication on auth server

### ISSUE THREAD

**Issue by i1990jain** [proyecto26/react-native-inappbrowser#36] opened 2019-01-07 10:27 UTC
```

async loginButton() {
 const deepLink = getDeepLink("home");
    const uniqueId = DeviceInfo.getUniqueID();
    const url = "https://backend.com/?redirect_uri=${deepLink}";
    console.log(url);
    console.log(uniqueId);
    try {
      await InAppBrowser.isAvailable();
      InAppBrowser.openAuth(url, deepLink, {
        // iOS Properties
        dismissButtonStyle: "cancel",
        preferredBarTintColor: "gray",
        preferredControlTintColor: "white",
        readerMode: false,
        // Android Properties
        showTitle: true,
        toolbarColor: "#E73139",
        secondaryToolbarColor: "black",
        enableUrlBarHiding: true,
        enableDefaultShare: true,
        forceCloseOnRedirection: false,
        // Specify full animation resource identifier(package:anim/name)
        // or only resource name(in case of animation bundled with app).
        animations: {
          startEnter: "slide_in_right",
          startExit: "slide_out_left",
          endEnter: "slide_in_right",
          endExit: "slide_out_left"
        },
        headers: {
          "my-custom-header": "backend"
        }
      }).then(result => {
        console.log(result);
        
      });
    } catch (error) {
      Alert.alert(error.message);
    }
  }

```

I am using the deep linking auth flow example mentioned in the description of the repo. I was able to successfully open the authentication flow in the browser. I am using a Laravel based server to authenticate the user. Once the user is autheticated the server responds with 
`return redirect('mobileapp://home?token='.$token);`

when this happens the browser closes off but then `console.log(result);` shows me `type:dismiss` as a result from the browser, I would also like to know if there is a possibility to handle the URL change in the browser component how we do with for WebView `onNavigationStateChange` with that way also I will have a possibility to see what is the current state of the browser and act accordingly.

**Comment by jdnichollsc** [comment] 2019-01-08 14:35
@i1990jain please attach more info, what platform are you testing?

**Comment by jdnichollsc** [comment] 2019-01-08 14:38
About the redirection, try using `Linking.addEventListener('url', ...)`

**Comment by i1990jain** [comment] 2019-01-08 15:15
> @i1990jain please attach more info, what platform are you testing?

I am testing both on android and iOS

**Comment by i1990jain** [comment] 2019-01-08 15:19
> About the redirection, try using `Linking.addEventListener('url', ...)`

well this is regarding the app I am talking about the fact that once the user is authenticated on the laravel based website which is open in the inappbrowser in am responding with 
`return redirect('mobileapp://home?token='.$token);`
Is that the right way to communicate the result back to the app or not ? 
As of now when I do this the inAppbrowser goes away and I just get type:dismiss in console.log

**Comment by jdnichollsc** [comment] 2019-01-08 16:00
About the redirect, it's different per platform:
- Android: `your_android_scheme://your_android_host/home?token=...`
- iOS: `your_CFBundleURLName://home?token=...`

Do you have the deep linking configuration already for Android (AndroidManifest.xml) and iOS (Info.plist)?

**Comment by i1990jain** [comment] 2019-01-08 16:15
yes I have configured these and the server responds based on the platform ... but in either of the case I just get type:dismiss as the result in the function 

```
"native-base": "^2.8.1",
    "react": "16.6.1",
    "react-native": "0.57.7",
  "react-navigation": "^3.0.8",
"react-native-inappbrowser-reborn": "^1.3.11",
```

**Comment by jdnichollsc** [comment] 2019-01-08 16:48
Ohh but what version of iOS? what version of Android? The last version of the plugin is working well in our app

<img width="783" alt="captura de pantalla 2019-01-08 a la s 11 45 42 a m" src="https://user-images.githubusercontent.com/2154886/50845597-400b6e80-133b-11e9-85b9-d6116dab8aca.png">

**Comment by i1990jain** [comment] 2019-01-08 19:35
Android 8.0.0
iOS 12.1.1

**Comment by i1990jain** [comment] 2019-01-08 19:37
Cannot you just a brief explaination about what and in which way the response should be returned from the server ?

**Comment by jdnichollsc** [comment] 2019-01-08 23:38
we have a redirection from the server to the deep linking of the app and when that url is detected by the plugin, the following response is returned: { type: 'success', url: `appscheme://...` }

**Comment by jdnichollsc** [comment] 2019-01-09 14:34
Very odd because we have the same configuration with Linking here https://github.com/proyecto26/react-native-inappbrowser/blob/master/index.js#L119

**Comment by jdnichollsc** [comment] 2019-01-09 14:37
Can you debug from the plugin and let me know?

**Comment by i1990jain** [comment] 2019-01-11 14:02
Ok so I tried using the same with iOS and it works perfectly but still I haven't been able to get it working for android 
tell me if I am going wrong anywhere with the app manifest

`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.mobileapp">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.CAMERA"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-feature android:name="android.hardware.camera" android:required="false" />
    <uses-feature android:name="android.hardware.camera.front" android:required="false" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:launchMode="singleTask"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:screenOrientation="portrait"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
        <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="mobileapp" android:host="mobile-host"/>            
    </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>`

**Comment by jdnichollsc** [comment] 2019-01-11 14:47
What's the redirection used from the server in the case of Android?

**Comment by i1990jain** [comment] 2019-01-11 16:01
I am redirecting to `"mobileapp://mobile-host/home?data="`

**Comment by jdnichollsc** [comment] 2019-01-11 19:46
mmm very odd, we have this Android intent:
```
<intent-filter>
    <action android:name="android.intent.action.VIEW" />
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />
    <data android:scheme="app-scheme" android:host="app-host" android:pathPrefix="" />
</intent-filter>
```

**Comment by jdnichollsc** [comment] 2019-01-14 21:59
can you debug and put a breakpoint here? https://github.com/proyecto26/react-native-inappbrowser/blob/master/index.js#L114

**Comment by sdsd08013** [comment] 2019-03-05 04:48
same issue, I encountered.

**Comment by jdnichollsc** [comment] 2019-03-05 06:52
@sdsd08013 please debug and let me know 🙏

**Comment by jdnichollsc** [comment] 2019-03-21 00:45
Any help is really appreciated!

**Comment by jdnichollsc** [comment] 2019-05-06 05:07
Ohhh you can't use `android:launchMode="singleTask"`

**Comment by viewpnt1** [comment] 2019-07-30 13:12
Encountered the same issue without `android:launchMode="singleTask"`. Anyone found a solution for this yet?

**Comment by viewpnt1** [comment] 2019-07-31 15:09
@jdnichollsc can you tell me what info you need from debugging, and is it native debug or js debug? I tried almost everything the result is always "dismiss". Also, I noticed that android:launchMode="singleTask"is present in the example app, but same thing happens with or without it.

**Comment by jdnichollsc** [comment] 2019-07-31 15:17
@viewpnt1 I

**Comment by jdnichollsc** [comment] 2019-07-31 15:19
@viewpnt1 let me know the url to debug your authentication because in my case it's working as expected, we're using okta to authenticate the users and the deep linking redirection works very well :)

**Comment by jdnichollsc** [comment] 2019-07-31 15:25
Check this example https://github.com/proyecto26/react-native-inappbrowser/blob/master/example/App.js#L107
The server should redirect to that `redirect_url` and you can add query string params too 👍

**Comment by viewpnt1** [comment] 2019-07-31 15:30
@jdnichollsc thanks for your response, but I think I'm not allowed to give you credentials because I'm working as a subcontractor and live database is used.
Could number of redirects be an issue here? I have 2 web redirects before final deeplink redirect.

**Comment by jdnichollsc** [comment] 2019-07-31 15:41
2 redirections? I'm not sure in that native aspect

**Comment by viewpnt1** [comment] 2019-07-31 16:25
I found this with JS debugging:

`return await Promise.race([open(startUrl, options), _waitForRedirectAsync(returnUrl)]);`

Promise.race result is always result from open() call and not _waitForRedirectAsync. If I comment out the following code:

`  try {
    return await Promise.race([open(startUrl, options), _waitForRedirectAsync(returnUrl)]);
    } catch(e){
        console.warn(e);

  } finally {
    //close();
    //Linking.removeEventListener('url', _redirectHandler);
    //_redirectHandler = null;
  }`

The _redirectHandler gets called and gets {type : success} along with the redirect url (the desired result).

So the question is, why is open() call getting always dismissed, and because of that wins the Promise.race?

**Comment by jdnichollsc** [comment] 2019-07-31 19:41
How are you redirecting from the backend? It's a little complicated without see that part

**Comment by jdnichollsc** [comment] 2019-07-31 19:44
The dismiss from Android is triggered from the [onDestroy method](https://github.com/proyecto26/react-native-inappbrowser/blob/master/android/src/main/java/com/proyecto26/inappbrowser/ChromeTabsManagerActivity.java#L69) of that Android Activity

**Comment by viewpnt1** [comment] 2019-07-31 19:55
Its laravel redirection.

`return redirect('myapp://myhost/login?', $queryString);`
(sends 302 status code)

The issue is that onDestroy is called before _redirectHandler. If I ignore onDismiss event, _redirectHandler gets called and I get the result I want, but the problem remains with handling user closing browser or errors...

**Comment by jdnichollsc** [comment] 2019-08-01 15:17
Maybe we can put a delay here, what do you think? Like this:
```
return await Promise.race([
  open(startUrl, options).then((result) => new Promise((resolve) => {
    // A delay to wait for the redirection or dismiss the browser
    setTimeout(() => resolve(result), 400)
  })),
  _waitForRedirectAsync(returnUrl)
])
```

What do you think? :)

**Comment by jdnichollsc** [comment] 2019-08-01 17:32
I don't like timeouts but ajam ¯\_(ツ)_/¯

**Comment by viewpnt1** [comment] 2019-08-19 17:27
I ended up discarding the result from `open`. I liked your proposal and have tried it many times with even longer timeouts but it just isn't working. Thanks for your support anyway :)

**Comment by Luke-Rogerson** [comment] 2019-08-19 18:05
@viewpnt1 I'm also facing the issue and trying to debug. Do you mean you are only awaiting the result of the second promise now?

**Comment by viewpnt1** [comment] 2019-08-19 23:11
@Luke-Rogerson yes

**Comment by jdnichollsc** [comment] 2019-08-19 23:59
> with even longer timeouts but it just isn't working

Stranger things

**Comment by Luke-Rogerson** [comment] 2019-08-20 07:21
> @Luke-Rogerson yes

Did that resolve the issue? From my perspective, it seems that `_waitForRedirectAsync` isn't waiting properly for the `success` event. What do you think?

**Comment by viewpnt1** [comment] 2019-08-20 08:03
@ it resolved the issue partially, since I cant handle errors now. If everything is ok, I get the result in _waitForRedirectAsync, and it works as intended. I tried native android debuging but didnt manage to find out what happens. The onDestroy method in activity gets called always and it sends event that results in type:dismiss. 

How many redirects you have in your flow?

**Comment by Luke-Rogerson** [comment] 2019-08-20 13:24
So one way I've been able to get back a `success`ful response is by using `Promise.all` to make sure that both promises are resolving before moving on. 

`try {
    return Promise.all([open(startUrl, options), _waitForRedirectAsync(returnUrl)])
  } finally {
...
  }`

@jdnichollsc Is this OK to do? I feel it is, as even if the response type is `dismiss` or `cancel` (say if the user clicks the close button), it will still resolve the promise and not reject? 

Also, should we set the `_redirectHandler` back to null at the start of the try block in ` _openAuthSessionPolyfillAsync`? This is because sometimes I'm gettting the `'InAppBrowser.openAuth is in a bad state. _redirectHandler is defined when it should not be.'` error because the `redirectHandler` isn't null.

I'm having an issue now where despite the `open` method getting called, the browser modal isn't always opening? Anyone encountered this before? Might be related to my changes, but I don't think so.

**Comment by jdnichollsc** [comment] 2019-08-20 17:00
> Is this OK to do?

What happens if the browser is closed but the redirection never responds? Because we have a conditional here to detect deep linking redirection: `if (event.url.startsWith(returnUrl))` 

> sometimes I'm gettting the error because the redirectHandler isn't null.

Can you share your code? You can only call `_openAuthSessionPolyfillAsync` once at a time.

**Comment by Luke-Rogerson** [comment] 2019-08-21 07:10
@jdnichollsc Could you have a look at my PR? Tell me what you think about my fixes! 🙂

**Comment by moak** [comment] 2019-08-23 14:44
Same issue here .. :( Working fine on IOS but getting { type: dismiss } on android.

**Comment by andresubri** [comment] 2019-09-03 19:48
I got tired of trying to find a solution, a workaround is to do.

```
    return await InAppBrowser.openAuth(
      authorizationEndpoint,
      redirectUrl,
      {
        // iOS Properties
        dismissButtonStyle: 'cancel',
        // Android Properties
        showTitle: false,
        enableUrlBarHiding: true,
        enableDefaultShare: false,
      },
    ).then(response => {
      if (response.type === 'success' && response.url) {
        return handleURL(response.url);
      }
      // Android bug: response.type is always dismiss, a workaround is to get the url directly with RN's API
      return Linking.getInitialURL().then(url => {
        if (url) {
          return handleURL(url);
        }
      });
    });
```

**Comment by jdnichollsc** [comment] 2019-09-03 21:13
Ok guys, debug **develop** branch and let me know if this PR works for you https://github.com/proyecto26/react-native-inappbrowser/pull/103/files

**Comment by jdnichollsc** [comment] 2019-09-03 21:37
Check the last version **3.1.0** and let me know 👍

**Comment by andresubri** [comment] 2019-09-04 03:16
Just tested
Added ` waitForRedirectDelay: 10000,`
The delay works but still `dismiss` is coming up

**Comment by giacomocerquone** [comment] 2019-09-09 08:31
Damn... I also ran this example configured by you https://github.com/proyecto26/react-native-inappbrowser/blob/master/example/App.js#L104 and I've got the same problem.
Actually when the redirects is done, the app shuts down and it won't open again and only when I manually open the app back I've got an alert with "type dismissed".

This is really blocking sadly :(

**Comment by viewpnt1** [comment] 2019-09-09 10:07
@giacomocerquone do you have more than 1 redirect in your login flow?

**Comment by giacomocerquone** [comment] 2019-09-09 10:11
@viewpnt1 as I said, I'm using the example https://github.com/proyecto26/react-native-inappbrowser/blob/master/example/App.js#L104 and as you can see there is 1 redirect in that login flow.

Plus I tried the deep link externally (just using Linking.openURL) and it is working. So can't understand why it's crashing...

**Comment by giacomocerquone** [comment] 2019-09-09 14:59
@jdnichollsc very good news guys!
I even managed to remove the error that brought @i1990jain to open this thread (I also think I solved the crash that I was experiencing too)

I previously updated my last comment saying that probably the problem relied in the Android API's I was using, but actually I was wrong.

The broken thing, at least for me, was this page here put up by the owner of this lib: https://github.com/proyecto26/react-native-inappbrowser/blob/gh-pages/index.html

Basically the way he links back to the app is faulty and it can crash your app and result in a "dismissed" action for the lib.
So I basically tried to switch to this page I put up (I put it on gh pages but it still gives back a 404): http://www.webdevout.net/test?04y&raw
and everything worked out nice and perfect for me.

Now, what this probably means?
While triaging this issue I've encountered some blog posts where there was written that in order to test deep linking you can't just open chrome and insert your custom link in the url bar for several reasons.
In fact, one advised way, is to use an "a" tag. Now I'm about to test it out with a meta tag and see what happens

**Comment by jdnichollsc** [comment] 2019-09-09 15:35
> I also ran this example configured by you https://github.com/proyecto26/react-native-inappbrowser/blob/master/example/App.js#L104

It looks like JS redirections doesn't work in the case of Android, only works with redirections from backend ([HTTP 302](https://en.wikipedia.org/wiki/HTTP_302)), check for more details => https://stackoverflow.com/a/41882732/1532821

**Comment by giacomocerquone** [comment] 2019-09-10 09:05
@jdnichollsc yes, in fact attaching the deep link url directly to auth0 (they obviously use a 302) it works gracefully
I'm about to prepare a pr for your example in order to put a link there instead of an automatic return to the app

**Comment by jdnichollsc** [comment] 2019-09-10 15:32
>Anyway sometimes my app keeps crashing...

Can you debug from Android Studio?

Maybe using a redirection from backend is much better from the example

**Comment by zealgit** [comment] 2019-11-11 06:04
I am still facing same issue of "type:dismiss", is this issue already bin fixed?

Can anyone help me with it please?

**Comment by jdnichollsc** [comment] 2019-11-12 06:34
@andresubri thanks for your help, it was fixed in the last version 3.3.0, let me know  👍 https://github.com/proyecto26/react-native-inappbrowser/releases/tag/v3.3.0

**Closed by jdnichollsc** 2019-11-12 06:34 UTC
Labels: bug, help wanted

**Comment by zealgit** [comment] 2019-11-12 07:33
@jdnichollsc I've just updated to version 3.3.0 and the issue of "type:dismiss" persists in Android.

Can you please help me with this?

**Comment by jdnichollsc** [comment] 2019-11-12 07:39
Please share more details of your error because I don't know what version of Android you're using, the backend redirection logic you have, the deep linking configuration you did in your project, etc 😅
PD: If this issue is urgent for you, you can contact Tidelift support too 🙂

**Comment by zealgit** [comment] 2019-11-12 07:48
I've followed same process for deep linking configuration suggested in the example, and redirecting to "appname://callback" url using laravel Redirect::to() function.

I am using Android 7.0 version device.

**Comment by giacomocerquone** [comment] 2019-11-12 08:17
Honestly @jdnichollsc I believe there is a huge misunderstanding with this library due to the example in the readme. I discovered this randomly after having spent a whole day to implement deep linking and the oatuh2 auth flow with an external provider.

I ported an entire expo app to a bare react native app and I used this module to replace the "authsession" module.
On expo I wasn't used to deep link back to the app after a successful authentication, instead I just awaited the value of the promise returned by the open method and we can do the same with this lib too.
The only thing that prevented us to do so, was this issue because the returned data sometimes were of type dismissed even when the authentication flow went fine and for the reason we were better off using the deep linking flow.

Do you confirm this or what I'm wrong about something?

**Comment by jdnichollsc** [comment] 2019-11-12 14:34
I don't understand you because we have the same logic from Expo, you need to configure deep linking in your app to be able to redirect the users from browser to the app again and we fixed the race condition issue with the promise when the browser is opened from Android, so check again and let me know, you can debug the JS code of this library from your project (node_modules) using React Native Debugger tool and let us know if the new validation using Linking is working as expected 🙂 https://github.com/expo/expo/blob/master/packages/expo-web-browser/src/WebBrowser.ts#L179

**Comment by jdnichollsc** [comment] 2019-11-12 17:21
@zealgit please check the `example` folder of this project and let me know if you can reproduce this issue 👍

**Comment by giacomocerquone** [comment] 2019-11-14 00:08
Sorry for the delay! Not appreciating the downvote, but still...

This is one thing:

```
InAppBrowser.openAuth(url, deepLink).then((response) => {
          if (response.type === 'success' &&
            response.url) {
            Linking.openURL(response.url)
          }
        })
```

and this is another:

```
InAppBrowser.openAuth(url, deepLink).then((response) => {
          if (response.type === 'success' &&
            response.url) {
              followingAuth(response.url)
          }
        })
```

My question was: deep linking configuration is needed for both ways or just for the first one?

**Comment by jdnichollsc** [comment] 2019-11-14 00:35
>after having spent a whole day
The downvote is about this, we spent more days creating this library, so you can create any pull request if you see an opportunity for improvement in this plugin 👍 

About `openAuth`, deep linking configured properly is required to use that method, otherwise we can't detect the redirection and you need to use `Linking` directly :)
For more details about `deep linking` configuration you can see the **example** project of this library:
- Android: https://github.com/proyecto26/react-native-inappbrowser/blob/master/example/android/app/src/main/AndroidManifest.xml#L27
- iOS: https://github.com/proyecto26/react-native-inappbrowser/blob/master/example/ios/example/Info.plist#L29

**Comment by jdnichollsc** [comment] 2019-11-15 08:22
Guys, FYI https://github.com/proyecto26/react-native-inappbrowser/releases/tag/v3.3.2
PD: `AppState` is required from **Android** to be able to get the last url when the `OnResume` event of the Android Activity is called after the redirection, if you see any other error please report in another issue 👍
