### ISSUE TITLE
How to disable opening urls in other apps? 

### ISSUE THREAD

**Issue by DilnaMohandasNT** [proyecto26/react-native-inappbrowser#166] opened 2020-07-01 08:26 UTC
Is there any way to control the deeplink to the other applications and open it in the browser itself?

for example if any youtube link is clicked it opens the youtube app, instead I want to open it in the In-app browser itself

**Comment by claudiozam** [comment] 2020-07-02 10:11
@DilnaMohandasNT please check https://github.com/proyecto26/react-native-inappbrowser/issues/107

**Comment by jdnichollsc** [comment] 2020-07-19 01:03
Duplicate of #107

**Closed by jdnichollsc** 2020-07-19 01:03 UTC
